name: example

on:
  workflow_dispatch:
    inputs:
      access:
        description: 'GCP IAM Role'
        required: true
      period:
        description: '有効期限（min）'
        required: true
        default: 15
      account:
        description: 'your account'
        required: true
      purpose:
        description: '付与理由（可能な限り具体的に）'
        required: true

env:
  IAM_PROJECT: your-gcp-project
  CONFIG_YAML_PATH: config.yml    

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install Pipenv
      working-directory: core    
      run: |
        pip install pipenv
    - uses: google-github-actions/setup-gcloud@master
      with:
       version: '290.0.0'
       service_account_key: ${{ secrets.GCP_SA_STG_KEY }}
       export_default_credentials: true
    - name: Install dependencies
      working-directory: core    
      run: |
        pipenv install
        echo $GOOGLE_APPLICATION_CREDENTIALS
        ls -la $GOOGLE_APPLICATION_CREDENTIALS
    - name: Request ACL
      run: |
        pipenv run start set
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        IAM_ACCESS: ${{ github.event.inputs.access }}
        IAM_TARGET_ACCOUNT: ${{ github.event.inputs.account }}
        IAM_PERIOD: ${{ github.event.inputs.period }}